config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :products



  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  get '/cart/tracking', to: 'orders#show', as: :tracking



  
  get 'welcome/home'
  root "welcome#home"
  get 'welcome/rest'
  get 'welcome/auto'
  get 'welcome/electronics'
  get 'welcome/fashion'
  get 'welcome/gs'
  get 'welcome/grocery'
  get 'welcome/furniture'
  get 'welcome/health'
  get 'welcome/repair'
  get 'welcome/recent'
  get 'welcome/popular'
  get 'welcome/events'
  get 'welcome/contact'
  get 'welcome/about'
  get 'welcome/search'
  get 'welcome/decor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # new routes
  resources :registeration_numbers do
    resources :orders, controller: 'registeration_numbers/orders'
  end
  post :get_cities_by_state,       action: :get_cities_by_state, controller: :products
end

app/models/shop.rb
class Shop < ApplicationRecord
	mount_uploader :imageshop, ImageUploader
	belongs_to :user
	has_many :products
	belongs_to :registeration_number, required: false
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @products = Product.all
  end

  # GET /shops/new
  def new
    @shop = current_user.build_shop
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    if params[:shop][:registeration_number].present?
      code = RegisterationNumber.where(code: params[:shop][:registeration_number]).first
      if code.present?
        @shop = current_user.build_shop(shop_params)
        @shop.user = current_user
        @shop.registeration_number_id = code.id
        respond_to do |format|
          if @shop.save
            format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
            format.json { render :show, status: :created, location: @shop }
          else
            format.html { render :new }
            format.json { render json: @shop.errors, status: :unprocessable_entity }
          end
        end
      else    
        respond_to do |format|
          format.html { redirect_to new_shop_path, notice: 'Shop was successfully created.'  }
          format.json { render json: {registeration: "Registeration Number not foud"}, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to new_shop_path, notice: 'Shop was successfully created.'   }
        format.json { render json: {registeration: "Registeration Number not foud"}, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :description, :imageshop, :location, :web, :email, :phone, :business, :category)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




    <body>

      <form >
      
        <h1>Add Your Shop</h1>
        
        <fieldset>
          <legend><span class="number">1</span>Your basic info</legend>
          <label for="name">Name:</label>
          <%= form.text_field :name, id: :shop_name %>
          
          <label for="mail">Email:</label>
          <%= form.text_field :email, id: :shop_email %>
          
          <label for="password">Description:</label>
          <%= form.text_area :description, id: :shop_description %>
          
          <label>Image:</label>
          <%= form.file_field :imageshop, id: :shop_imageshop %>
        </fieldset>
        
        <fieldset>
          <legend><span class="number">2</span>Important Infos</legend>
          <label for="bio">Location:</label>
          <%= form.text_field :location, id: :shop_location %>
        </fieldset>
        <fieldset>
          <label for="bio">Registeration Number:</label>
          <%= form.text_field :registeration_number, id: :registeration_number %>
        </fieldset>
        <fieldset>
        <label for="job">Website:</label>
        <%= form.text_field :web, id: :shop_web %>
        
          <label>Phone Number:</label>
         <%= form.text_field :phone, id: :shop_phone %><br><label class="light" for="business">Business Type</label>
            <%= form.select :busness, ['Service Provider', 'Products Based Business'] %><label class="light" for="design">Business Category</label><br>
          <%= form.select :category, ['Electronics', 'Fashion', 'Furniture', 'Kitchen Stores', 'Restraunts', 'Hotels', 'General Stores', 'Grocery Stores'] %>
        
        </fieldset>
        <div class="bobo" style="text-align:center; padding:0; margin:0;">
    <%= form.submit class: "btn-success" %>
  </div>

      </form>
      
    </body>
</html>
<% end %>


<style>
*, *:before, *:after {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

body {
  font-family: 'Nunito', sans-serif;
  color: #384047;
  padding: 0px;
  margin: 0px;
}

form {
  max-width: 300px;
  margin: 10px auto;
  padding: 10px 20px;
  background: #f4f7f8;
  border-radius: 8px;
}

h1 {
  margin: 0 0 30px 0;
  text-align: center;
  color: #000;
}

input[type="text"],
input[type="password"],
input[type="date"],
input[type="datetime"],
input[type="email"],
input[type="number"],
input[type="search"],
input[type="tel"],
input[type="time"],
input[type="url"],
textarea,
select {
  background: rgba(255,255,255,0.1);
  border: none;
  font-size: 16px;
  height: auto;
  margin: 0;
  outline: 0;
  padding: 15px;
  width: 100%;
  background-color: #e8eeef;
  color: #8a97a0;
  box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
  margin-bottom: 30px;
}

input[type="radio"],
input[type="checkbox"] {
  margin: 0 4px 8px 0;
}

select {
  padding: 6px;
  height: 32px;
  border-radius: 2px;
}



fieldset {
  margin-bottom: 30px;
  border: none;
}

legend {
  font-size: 1.4em;
  margin-bottom: 10px;
}

label {
  display: block;
  margin-bottom: 8px;
}

label.light {
  font-weight: 300;
  display: inline;
}

.number {
  background-color: #5fcf80;
  color: #fff;
  height: 30px;
  width: 30px;
  display: inline-block;
  font-size: 0.8em;
  margin-right: 4px;
  line-height: 30px;
  text-align: center;
  text-shadow: 0 1px 0 rgba(255,255,255,0.2);
  border-radius: 100%;
}

@media screen and (min-width: 480px) {

  form {
    max-width: 480px;
  }

}
</style>

app/views/shops/edit.html.erb
<style>
.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  color: #fff;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #fff;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  top: 0;
  right: 25px;
  font-size: 36px;

}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<div class="dark-bg sticky-top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                            <span style="font-size:30px;cursor:pointer;" onclick="openNav()">&#9776; </span>
                            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                                <ul class="navbar-nav">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/fashion">Fashion</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/electronics">Electronics</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/furniture">Furniture</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/kitchen">Kitchen</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/grocery">Grocery</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/restraunts">Retraunts</a>
                                    </li>

                                    <li class="nav-item active">
                                        <a class="nav-link" href="/welcome/events">Events</a>
                                    </li>
                                    
                                   
                                    <% if user_signed_in? %>
                                    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light top-btn" %></li>
                                    <% else %>
                                    <li><a href="/users/sign_in" class="btn btn-outline-light top-btn">SignUp/SignIn</a></li>
                                   <% end %>
                                </ul>
                            </div>
                            <li class="nav-item active">
                                        <a class="nav-link" href="/"><img src="/assets/search.png" style="width:30px; height:30px; margin-bottom:8px;"></a>
                                    </li>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
<body>
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a class="navbar-brand" style="text-align:center;" href="/">NearClick</a>
  <br>
  <% if user_signed_in? %>
  <p style="text-align:center;">Welcome <%= current_user.username %></p>
  <% else %>
  <p style="text-align:center;">Welcome Guest</p>
  <% end %>
  <% if current_user&.shop %>
  <a href="/products/new">Add Product</a>
  <%= link_to 'Manage Shop', current_user.shop %>
  <% else %>
  <a href="#"><span>0</span> Your Cart</a>
  <a href="#">Wishlist</a>
  <% end %>
  <a href="/welcome/about">About</a>
  <a href="/welcome/contact">Contact</a>
</div>
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<div class="broke" style="text-align:center;">
<%= link_to 'Back', shops_path, class: "btn btn-danger" %>
</div>
 <footer class="main-block dark-bg" style="padding-bottom:30px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright &copy; 2019  Nearclick. All rights reserved. </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <ul>
                            <li><a href="#"><span class="ti-facebook"></span></a></li>
                            <li><a href="#"><span class="ti-twitter-alt"></span></a></li>
                            <li><a href="#"><span class="ti-instagram"></span></a></li>
                        </ul>

                        <ul>
                         <li class="nav-item active">
                                        <a class="nav-link" style="font-size:30px; font-weight:700; color:#ffffff" href="/welcome/about">About</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" style="font-size:30px; font-weight:700; color:#ffffff" href="/welcome/contact">Contact</a>
                                    </li>

                                </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Imageshop</th>
      <th>Business type</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.description %></td>
        <td><%= shop.imageshop %></td>
        <td><%= shop.business_type %></td>
        <td><%= shop.category %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<br>
<br>
<br>


<%= render 'form', shop: @shop %>

<div class="broke" style="text-align:center;">
<%= link_to 'Back', shops_path, class: "btn btn-danger" %>
</div>
 

app/views/shops/show.html.erb
<br>
<br>
<br>
<body>



    <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title" style="text-align:center;"><%= @shop.name %>'s Contact Info</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
         <h3><b>Location:</b></h3><br>
         <p><%= @shop.location %></p>
         <hr>

         <h3><b>Phone:</b></h3><br>
         <p><%= @shop.phone %></p>
         <hr>

         <h3><b>Website:</b></h3><br>
         <p><%= @shop.web %></p>
         <hr>

         <h3><b>Email:</b></h3><br>
         <p><%= @shop.email %></p>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>

  <div id="colorlib-page">

    <div id="colorlib-main">
      <div class="hero-wrap js-fullheight" style="background-image: url(/assets/bg_1.jpg);" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="js-fullheight d-flex justify-content-center align-items-center">
          <div class="col-md-8 text text-center">
            <div class="img mb-4"><img src="<%= @shop.imageshop %>" style="width:150px; height:150px; border-radius: 50%;"></div>
            <div class="desc">
              <h2 class="subheading"><%= @shop.category %></h2>
              <h1 class="mb-4"><%= @shop.name %></h1>
              <p class="mb-4"><%= @shop.description %></p>
              <p class="btn-custom" data-toggle="modal" data-target="#myModal">Contact Shop </p>
              <% if current_user=(@shop.user) %>
<%= link_to 'Edit', edit_shop_path(@shop), class: 'btn btn-danger' %>
<% end %>
            </div>
          </div>
        </div>
      </div>
      <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-2">
          <div class="col-md-7 heading-section text-center ftco-animate">
            <h2 class="mb-4">Products</h2>
            <p>All the products listed here are directly sold by <%= @shop.name %> and NearClick is just there delivery partner, we deliver the product as it is without opening the package.</p>
          </div>
        </div>
        <div class="row">





              <% @products.each do |product| %>
          <div class="col-md-4">
            <div class="blog-entry ftco-animate">
              <a href="#" class="img img-2"><img src="<%= product.image %>" style="width:300px; height:250px;"> </a>
              <div class="text text-2 pt-2 mt-3">
                <span class="category mb-3 d-block"><a href="#"><%= product.name %></a></span>
                <h3 class="mb-4"><a href="#"><%= product.category %></a></h3>
                <h3 class="mb-4"><a href="#">Rs: <%= product.price %></a></h3>
                <p class="mb-4"><%= product.description %></p>
                <div class="author mb-4 d-flex align-items-center">
                  <div class="img mb-4"><img src="<%= @shop.imageshop %>" style="width:50px; height:50px; border-radius: 50%;"></div>
                  <div class="ml-3 info">
                    <span>Sold By</span>
                    <h3><a href="#"><%= @shop.name %></a></h3>
                  </div>
                </div>
                <div class="meta-wrap align-items-center">
                  
                  <div class="half">
                    <p><a href="#" class="btn btn-success">Order Now </a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </section>

  </body>
</html>