config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :products



  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  get '/cart/tracking', to: 'orders#show', as: :tracking



  
  get 'welcome/home'
  root "welcome#home"
  get 'welcome/rest'
  get 'welcome/auto'
  get 'welcome/electronics'
  get 'welcome/fashion'
  get 'welcome/gs'
  get 'welcome/grocery'
  get 'welcome/furniture'
  get 'welcome/health'
  get 'welcome/repair'
  get 'welcome/recent'
  get 'welcome/popular'
  get 'welcome/events'
  get 'welcome/contact'
  get 'welcome/about'
  get 'welcome/search'
  get 'welcome/decor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # new routes
  resources :registeration_numbers do
    resources :orders, controller: 'registeration_numbers/orders'
  end
  post :get_cities_by_state,       action: :get_cities_by_state, controller: :products
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items, class_name: 'OrderItem'
	has_many :products, through:  :items
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@order = current_cart.order
	end

	def show
		@orders = Order.all
	end

	def create
		@order = current_cart.order
		if @order.update_attributes(order_params.merge(status:'open'))
			session[:cart_token] = nil
			redirect_to action: 'show'
		else
			render:new
		end
	end

	private
	def order_params
		params.require(:order).permit(:first_name, :las_name, :city, :mobile_number, :delivery_address, :email, :pincode, :tracking)
	end

end

app/controllers/registeration_numbers/orders_controller.rb
class RegisterationNumbers::OrdersController < RegisterationNumbersController
	before_action :check_rn_belongs_to_right_agent

	def index
		@shops = @rn.shops
	end

	private
	def check_rn_belongs_to_right_agent
		@rn = RegisterationNumber.includes([:shops => [:products => [:items]]]).find(params[:registeration_number_id])
		redirect_to "/" if !(current_user && @rn.user.id  == current_user.id)
	end
end

app/helpers/registeration_numbers/orders_helper.rb
module RegisterationNumbers::OrdersHelper
end

app/views/orders/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/assets/checkout.css">
    <link rel="stylesheet" href="/assets/bootstrap.min.css">
    <script src="/assets/bootstrap.min.js"></script>
    <title>Check Out</title>
  </head>
  <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#"><img src="" alt="" class="img-fluid"></a>
                
              
                <div>
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                                <i class="fa fa-cart-arrow-down d-block" aria-hidden="true"></i>
                        <p><span class="text-color">Cart ------------ Delivery &amp; Billing Address ------------ </span>
                         Payment</p>
                    </li>
                    <li class="nav-item">
                        <div class="user">
                            <span class="h4"> Hello</span>
                        </div>
                    </li>
                  </ul>
                  
                </div>
              </nav>

        <div class="container mt-5">
            <div class="row">
                <div class="col col-md-8">
                    <div class="order-summary">
                            <div id="accordion">
                                    <div class="card mb-1">
                                      <div class="card-header" id="summary">
                                        <h5 class="mb-0">
                                          <button class="btn" data-toggle="collapse" data-target="#one" aria-expanded="true" aria-controls="one">
                                                <strong>Need Help?</strong>
                                                <span>(<%= link_to pluralize(current_cart.items_count, 'item'), cart_path %>)</span>
                                          </button>
                                        </h5>
                                      </div>
                                  
                                      <div id="one" class="collapse" aria-labelledby="summary" data-parent="#accordion">
                                        <div class="card-body">
                                              <div class="container">
                                                  <div class="col col-md-8">
                                                    <div class="box"> 
                                                        <div class="row">
                                                                <div class="col-md-5">
                                                                    <img src="/assets/help.png" alt="" class="img-fluid">
                                                                </div>
                                                                <div class="col col-md-7">
                                                                    <ul>
                                                                        <li>Need Help With Delivery.</li>
                                                                        <li>If you need any help regarding delivery.</li>
                                                                        <li><span class="text-color"><a href="/welcome/contact">Contact Us</a></span></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                    </div>

                                                  </div>
                                              </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                    </div>

                    <div class="form-checkOut">
                            <div id="accordion">
                                    <div class="card">
                                      <div class="card-header" id="form-checkOut">
                                        <h5 class="mb-0">
                                          <button class="btn" data-toggle="collapse" data-target="#two" aria-expanded="true" aria-controls="two">
                                                <strong class="text-uppercase">Shipping &amp; Billing Details</strong>
                                          </button>
                                        </h5>
                                      </div>
                                  
                                      <div id="two" class="collapse show" aria-labelledby="form-checkOut" data-parent="#accordion">
                                        <div class="card-body">
                                                
                                                  <%= form_for @order, url: checkout_path do |f| %>
                                                        <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                         
                                                          <%= f.text_field :first_name, :class => 'lala', placeholder: "Your First Name" %>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          
                                                          <%= f.text_field :last_name, :class => 'lala', placeholder: "Your Last Name" %>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          
                                                          <%= f.text_field :mobile_number, :class => 'lala', placeholder: "Your Valid Mobile Number" %>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                        
                                                          <%= f.text_field :email, :class => 'lala', placeholder: "Your Email Address" %>
                                                        </div>
                                                    </div>
                                                        <div class="form-group">
                                                                <div class="d-flex justify-content-between">
                                                         
                                                          <%= f.text_field :delivery_address, :class => 'lala', placeholder: "Complete Delivery Addresss" %>
                                                        </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                       
                                                          <%= f.text_field :city, :class => 'lala', placeholder: "Delivery City" %>
                                                        </div>
                                                    </div>

                                                    <div class="form-group">
                                                            <div class="d-flex justify-content-between">
                                                          <%= f.text_field :pincode, :class => 'lala', placeholder: "Pincode" %>
                                                        </div>
                                                    </div>

                                                    
                                                        <div class="dim" style="padding:0; margin:0;">
                                                              <%= f.submit "Save & Continue", class: "btn-success" %>
                                                            </div>
                                                              <% end %>
                                                      
                                        </div>
                                      </div>
                                    </div>
                                    </div>
                    </div>

                </div>
                <div class="col col-md-4">
                    <div class="box">
                        <ul class="d-flex justify-content-between">
                            <li>
                                <p>Item Total</p>
                            </li>
                            <li>
                                <strong>Rs. <%= current_cart.sub_total %></strong>
                            </li>
                        </ul>
                        <ul class="d-flex justify-content-between">
                                <li>
                                    <p>Shipping &amp; Handling <span class="text-color">(free)</span></p>
                                </li>
                                <li>
                                    <strong>Rs. <%= current_cart.sub_total %></strong>
                                </li>
                            </ul>
                            <hr>
                            <ul class="d-flex justify-content-between">
                                    <li>
                                        <p>You Pay
                                            <br>
                                            <span class="text-muted"><small>(Including all Taxes)</small></span>
                                        </p>
                                    </li>
                                    <li>
                                            <strong>Rs. <%= current_cart.sub_total %></strong>
                                        </li>
                                </ul>
                    </div>
                </div>
            </div>
        </div>

<style>
.lala {
    color: #999;
    font-weight: bold;
    font-size: 24px;
    padding: 10px;
    border: 2px solid #999;
    border-radius: 25px;
}
</style>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/orders/order_status.html.erb
<!doctype html>
<html>
<head>
<title>Shipment Track Widget Flat Responsive Widget Template :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Shipment Track Widget Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href="/assets/tro.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
	<% if @order.tracking == "Order Recived" %>
<div class="content">
	<div class="content1">
		<h2>Order Details</h2>
	</div>
	<div class="content2">
		<%if @order.first_name and @order.last_name%>
			<div class="content2-header1">
				<p>Name : <span><%= @order.first_name %> <%= @order.last_name %> </span></p>
			</div>
		<%end%>
		<%if @order.mobile_number %>
		<div class="content2-header1">
			<p>Contact Number : <span><%= @order.mobile_number%></span></p>
		</div>
		<%end%>
		<%if @order.email %>		
		<div class="content2-header1">
			<p>Email : <span><%= @order.email%></span></p>
		</div>
		<%end%>
		<%if @order.tracking %>				
		<div class="content2-header1">
			<p>Tracking status : <span><%= @order.tracking%></span></p>
		</div>
		<%end%>
		<%if @order.created_at %>				
		<div class="content2-header1">
			<p>Order Placed Date : <span><%= @order.created_at%></span></p>
		</div>
		<%end%>
		<div class="clear"></div>
	</div>
</div>

<div class="header">
	<h1>Shipment Track</h1>
</div>
<div class="content">
	<div class="content1">
		<h2>Order Tracking: Order No: <%= params[:order_number] if params[:order_number]%></h2>
	</div>
	<div class="content2">
		<div class="content2-header1">
			<p>Shipped Via : <span>Denny Dots Originals</span></p>
		</div>
		<div class="content2-header1">
			<p>Status : <span><%= @order.tracking %></span></p>
		</div>
		<div class="content2-header1">
			<p>Expected Time : <span>Within 10 Days</span></p>
		</div>

		<div class="clear"></div>
	</div>
	
	<div class="content3">
        <div class="shipment">
			<div class="confirm">
                <div class="imgcircle">
                    <img src="/assets/confirm.png" alt="confirm order">
            	</div>
				<span class="line"></span>
				<p>Order Recived</p>
			</div>

			<div class="quality">
				<div class="imgcircle">
                	<img src="/assets/quality.png" alt="quality check">
            	</div>
				<span class="line"></span>
				<p>Quality Check</p>
			</div>
			<div class="dispatch">
				<div class="imgcircle">
                	<img src="/assets/dispatch.png" alt="dispatch product">
            	</div>
				<span class="line"></span>
				<p>Out For Delivery</p>
			</div>
			<div class="delivery">
				<div class="imgcircle">
                	<img src="/assets/delivery.png" alt="delivery">
				</div>
				<p>Shipment Completed</p>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<% end %>


</body>
</html>































<% if @order.tracking == "Quality Check" %>
	<div class="content">
	<div class="content1">
		<h2>Order Details</h2>
	</div>
	<div class="content2">
		<%if @order.first_name and @order.last_name%>
			<div class="content2-header1">
				<p>Name : <span><%= @order.first_name %> <%= @order.last_name %> </span></p>
			</div>
		<%end%>
		<%if @order.mobile_number %>
		<div class="content2-header1">
			<p>Contact Number : <span><%= @order.mobile_number%></span></p>
		</div>
		<%end%>
		<%if @order.email %>		
		<div class="content2-header1">
			<p>Email : <span><%= @order.email%></span></p>
		</div>
		<%end%>
		<%if @order.tracking %>				
		<div class="content2-header1">
			<p>Tracking status : <span><%= @order.tracking%></span></p>
		</div>
		<%end%>
		<%if @order.created_at %>				
		<div class="content2-header1">
			<p>Order Placed Date : <span><%= @order.created_at%></span></p>
		</div>
		<%end%>
		<div class="clear"></div>
	</div>
</div>

<div class="header">
	<h1>Shipment Track</h1>
</div>
<div class="content">
	<div class="content1">
		<h2>Order Tracking: Order No: <%= params[:order_number] if params[:order_number]%></h2>
	</div>
	<div class="content2">
		<div class="content2-header1">
			<p>Shipped Via : <span>Denny Dots Originals</span></p>
		</div>
		<div class="content2-header1">
			<p>Status : <span><%= @order.tracking %></span></p>
		</div>
		<div class="content2-header1">
			<p>Expected Time : <span>Within 10 Days</span></p>
		</div>

		<div class="clear"></div>
	</div>
	
	<div class="content3">
        <div class="shipment">
			<div class="confirm">
                <div class="imgcircle">
                    <img src="/assets/confirm.png" alt="confirm order">
            	</div>
				<span class="line"></span>
				<p>Order Recived</p>
			</div>

			<div class="qualitytwo">
				<div class="imgcircle">
                	<img src="/assets/quality.png" alt="quality check">
            	</div>
				<span class="line"></span>
				<p>Quality Check</p>
			</div>
			<div class="dispatch">
				<div class="imgcircle">
                	<img src="/assets/dispatch.png" alt="dispatch product">
            	</div>
				<span class="line"></span>
				<p>Out for delivery</p>
			</div>
			<div class="delivery">
				<div class="imgcircle">
                	<img src="/assets/delivery.png" alt="delivery">
				</div>
				<p>Shipment Completed</p>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
		<% end %>







		<% if @order.tracking == "Out for delivery" %>
	<div class="content">
	<div class="content1">
		<h2>Order Details</h2>
	</div>
	<div class="content2">
		<%if @order.first_name and @order.last_name%>
			<div class="content2-header1">
				<p>Name : <span><%= @order.first_name %> <%= @order.last_name %> </span></p>
			</div>
		<%end%>
		<%if @order.mobile_number %>
		<div class="content2-header1">
			<p>Contact Number : <span><%= @order.mobile_number%></span></p>
		</div>
		<%end%>
		<%if @order.email %>		
		<div class="content2-header1">
			<p>Email : <span><%= @order.email%></span></p>
		</div>
		<%end%>
		<%if @order.tracking %>				
		<div class="content2-header1">
			<p>Tracking status : <span><%= @order.tracking%></span></p>
		</div>
		<%end%>
		<%if @order.created_at %>				
		<div class="content2-header1">
			<p>Order Placed Date : <span><%= @order.created_at%></span></p>
		</div>
		<%end%>
		<div class="clear"></div>
	</div>
</div>

<div class="header">
	<h1>Shipment Track</h1>
</div>
<div class="content">
	<div class="content1">
		<h2>Order Tracking: Order No: <%= params[:order_number] if params[:order_number]%></h2>
	</div>
	<div class="content2">
		<div class="content2-header1">
			<p>Shipped Via : <span>Denny Dots Originals</span></p>
		</div>
		<div class="content2-header1">
			<p>Status : <span><%= @order.tracking %></span></p>
		</div>
		<div class="content2-header1">
			<p>Expected Time : <span>Within 10 Days</span></p>
		</div>

		<div class="clear"></div>
	</div>
	
	<div class="content3">
        <div class="shipment">
			<div class="confirm">
                <div class="imgcircle">
                    <img src="/assets/confirm.png" alt="confirm order">
            	</div>
				<span class="line"></span>
				<p>Order Recived</p>
			</div>

			<div class="qualitytwo">
				<div class="imgcircle">
                	<img src="/assets/quality.png" alt="quality check">
            	</div>
				<span class="line"></span>
				<p>Quality Check</p>
			</div>
			<div class="dispatchtwo">
				<div class="imgcircle">
                	<img src="/assets/dispatch.png" alt="dispatch product">
            	</div>
				<span class="line"></span>
				<p>Out for delivery</p>
			</div>
			<div class="delivery">
				<div class="imgcircle">
                	<img src="/assets/delivery.png" alt="delivery">
				</div>
				<p>Shipment Completed</p>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
		<% end %>









		<% if @order.tracking == "Shipment Completed" %>
	<div class="content">
	<div class="content1">
		<h2>Order Details</h2>
	</div>
	<div class="content2">
		<%if @order.first_name and @order.last_name%>
			<div class="content2-header1">
				<p>Name : <span><%= @order.first_name %> <%= @order.last_name %> </span></p>
			</div>
		<%end%>
		<%if @order.mobile_number %>
		<div class="content2-header1">
			<p>Contact Number : <span><%= @order.mobile_number%></span></p>
		</div>
		<%end%>
		<%if @order.email %>		
		<div class="content2-header1">
			<p>Email : <span><%= @order.email%></span></p>
		</div>
		<%end%>
		<%if @order.tracking %>				
		<div class="content2-header1">
			<p>Tracking status : <span><%= @order.tracking%></span></p>
		</div>
		<%end%>
		<%if @order.created_at %>				
		<div class="content2-header1">
			<p>Order Placed Date : <span><%= @order.created_at%></span></p>
		</div>
		<%end%>
		<div class="clear"></div>
	</div>
</div>

<div class="header">
	<h1>Shipment Track</h1>
</div>
<div class="content">
	<div class="content1">
		<h2>Order Tracking: Order No: <%= params[:order_number] if params[:order_number]%></h2>
	</div>
	<div class="content2">
		<div class="content2-header1">
			<p>Shipped Via : <span>Denny Dots Originals</span></p>
		</div>
		<div class="content2-header1">
			<p>Status : <span><%= @order.tracking %></span></p>
		</div>
		<div class="content2-header1">
			<p>Expected Time : <span>Within 10 Days</span></p>
		</div>

		<div class="clear"></div>
	</div>
	
	<div class="content3">
        <div class="shipment">
			<div class="confirm">
                <div class="imgcircle">
                    <img src="/assets/confirm.png" alt="confirm order">
            	</div>
				<span class="line"></span>
				<p>Order Recived</p>
			</div>

			<div class="qualitytwo">
				<div class="imgcircle">
                	<img src="/assets/quality.png" alt="quality check">
            	</div>
				<span class="line"></span>
				<p>Quality Check</p>
			</div>
			<div class="dispatchtwo">
				<div class="imgcircle">
                	<img src="/assets/dispatch.png" alt="dispatch product">
            	</div>
				<span class="line"></span>
				<p>Out for delivery</p>
			</div>
			<div class="deliverytwo">
				<div class="imgcircle">
                	<img src="/assets/delivery.png" alt="delivery">
				</div>
				<p>Shipment Completed</p>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
		<% end %>

app/views/orders/order_tracking.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Contact V13</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/assets/util.css">
	<link rel="stylesheet" type="text/css" href="/assets/trako.css">
</head>
<body>


<div class="container-contact100">
	<div class="contact100-map" id="google_map" data-map-x="40.722047" data-map-y="-73.986422" data-pin="/assets/map-marker.png" data-scrollwhell="0" data-draggable="1">
	</div>
	<div class="contact100-more">
		<i class="zmdi zmdi-phone-in-talk"></i>
		 +91 9748 444 800
	</div>
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>The Order number you tried is not associated with any order in our sytem please order something and come back..</p>
  </div>
</div>
<div class="wrap-contact100">
 <form action="/order_tracking" method="get">
	<form class="contact100-form validate-form">
		<span class="contact100-form-title">
			Track Your Order
		</span>

		<div class="wrap-input100 validate-input" data-validate="Number is required">
			<span class="label-input100">Order No.</span>
			<input id="order_number" class="input100" type="text" name="order_number" placeholder="Order Number...">
			<span class="focus-input100"></span>
		</div>
				<div class="container-contact100-form-btn">
			<div class="wrap-contact100-form-btn">
				<div class="contact100-form-bgbtn"></div>
 			    <button type="submit" class="contact100-form-btn" onclick="checkOrderNumber()">Track</button> 
			</div>
		</div>
	</form>
</div>
</div>
<div id="dropDownSelect1"></div>
<div class="home">
</div>

<style>
.container-contact100 {
    background-image: url('/assets/vehicle_tracking_slide1.jpg');
    background-repeat: no-repeat;
    background-size: 50% 100%;
}
</style>
<script src="/assets/trako.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
</body>
</html>

<script type="text/javascript">
function checkOrderNumber(){
	var number=document.getElementById("order_number").value;  
	if (number === undefined || number === null || number == ""){
		alert("Pleae enter Order number.");
	}else{
	}
}
</script>

app/views/orders/show.html.erb
<br>
<br>

<div class="jumbotron text-xs-center">
  <h1 class="display-3">Thank You!</h1>
  <p class="lead"><strong>We Wil contact you</strong> When your order will be dispatched from our seller.</p>
  <hr>
  <p>
    Having trouble? <a href="/welcome/contact">Contact us</a>
  </p>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="/welcome/home" role="button">Continue to homepage</a>
  </p>
</div>