config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :products



  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  get '/cart/tracking', to: 'orders#show', as: :tracking



  
  get 'welcome/home'
  root "welcome#home"
  get 'welcome/rest'
  get 'welcome/auto'
  get 'welcome/electronics'
  get 'welcome/fashion'
  get 'welcome/gs'
  get 'welcome/grocery'
  get 'welcome/furniture'
  get 'welcome/health'
  get 'welcome/repair'
  get 'welcome/recent'
  get 'welcome/popular'
  get 'welcome/events'
  get 'welcome/contact'
  get 'welcome/about'
  get 'welcome/search'
  get 'welcome/decor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # new routes
  resources :registeration_numbers do
    resources :orders, controller: 'registeration_numbers/orders'
  end
  post :get_cities_by_state,       action: :get_cities_by_state, controller: :products
end

app/models/registeration_number.rb
class RegisterationNumber < ApplicationRecord
	before_save :generate_code
	belongs_to :user
	has_many :shops
	
	private
	def generate_code
    self.code = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.where(code: random_token).exists?
    end
  end
end

app/controllers/registeration_numbers/orders_controller.rb
class RegisterationNumbers::OrdersController < RegisterationNumbersController
	before_action :check_rn_belongs_to_right_agent

	def index
		@shops = @rn.shops
	end

	private
	def check_rn_belongs_to_right_agent
		@rn = RegisterationNumber.includes([:shops => [:products => [:items]]]).find(params[:registeration_number_id])
		redirect_to "/" if !(current_user && @rn.user.id  == current_user.id)
	end
end

app/controllers/registeration_numbers_controller.rb
class RegisterationNumbersController < ApplicationController
	before_action :check_agent

	def new

	end

	def index
		@numbers = current_user.registeration_numbers
	end

	def create
		number = current_user.registeration_numbers.create()
		redirect_to registeration_number_path number.id
	end

	def show
		@number = current_user.registeration_numbers.find(params[:id])
	end

	private
	def check_agent
		current_user && current_user.is_agent?
	end
end

app/helpers/registeration_numbers/orders_helper.rb
module RegisterationNumbers::OrdersHelper
end

app/helpers/registeration_numbers_helper.rb
module RegisterationNumbersHelper
end

app/views/registeration_numbers/index.html.erb
<div class="container" style="margin-top: 200px">
	<% @numbers.each.with_index(1) do |number,i| %>
		<a href="<%=registeration_number_orders_path(number.id)%>"><h1><%= i %>. <%= number.code %></h1></a>	
	<% end %>
	<%= form_with(model: RegisterationNumber.new, local: true) do |form| %>
	 
	  <div class="actions">
	    <%= form.submit "Generate Code", class: "btn btn-primary", style: 'width: 500px' %>
	  </div>
	<% end %>

</div>	

app/views/registeration_numbers/new.html.erb
<%= form_with(model: RegisterationNumber.new, local: true,html:  {style: 'margin-top: 200px'}) do |form| %>
 
  <div class="actions">
    <%= form.submit "Generate Code", class: "btn btn-primary", style: 'width: 500px' %>
  </div>
<% end %>

app/views/registeration_numbers/show.html.erb
<div class="container" style="margin-top: 200px">
	<h1><%= @number.code %></h1>	
</div>	